strWert1 = input("Eingabe Wert 1: ")
floatWert1 = float (strWert1)
strWert2 = input("Eingabe Wert 2: ")
floatWert2 = float (strWert2)
strWert3 = input("Eingabe Wert 3: ")
floatWert3 = float (strWert3)

print("Summe von Wert 1, Wert 2, Wert 3: ",floatWert1 + floatWert2 + floatWert3)
print("Multiplikation von Wert 1 und Wert 2: ", floatWert1 * floatWert2)
print("Division von Wert 3 und Wert 1: ", floatWert3 / floatWert1)
print("Differenz von Wert 2 und Wert 3: ", floatWert2 - floatWert3)